import { redrawTag } from "./redrawTag.function";
import { tagElement } from "./tagElement";
export * from "./ElementTargetEvent.interface";
export * from "./tag";
export * from "./html";
export * from "./errors";
export * from "./Subject";
export * from "./isInstance";
export * from "./ValueSubject";
export * from "./watch.function";
export * from "./TagSupport.class";
export * from "./redrawTag.function";
export * from "./interpolateElement";
export { tagElement } from "./tagElement";
export { Tag } from "./Tag.class";
export { runBeforeRender } from "./tagRunner";
export { setUse } from "./setUse.function";
export { providers } from "./providers";
export { set } from "./set.function";
export { setLet } from "./setLet.function";
export { setProp } from "./setProp.function";
export * from "./onInit";
export * from "./onDestroy";
export * from "./getCallback";
export declare const hmr: {
    tagElement: typeof tagElement;
    redrawTag: typeof redrawTag;
};
